apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golist-dev

bases:
- github.com/christianh814/golist-frontend/deploy

resources:
- golist-frontend-ingress.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: golist-frontend-config
    patch: |-
      - op: replace
        path: /data/config.json
        value: '{"api": "http://golist-api.7f000001.nip.io/api/products"}'
