apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: formengine-tform-dev-golist-frontend
  namespace: argocd
spec:
  source:
    path: apps/golist-frontend
    repoURL: 'https://github.com/merikan/golist'
    targetRevision: main
  destination:
    namespace: 'golist-dev'
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
