apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golist-dev

bases:
- github.com/christianh814/golist-api/deploy

resources:
- golist-api-ingress.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: golist-api-config
    patch: |-
      - op: replace
        path: /data/config.json
        value: '{"connection_string":"golist:golist@tcp(dev-golist-db-mariadb:3306)/golist","port":8080}'
